---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Frustration
description: Guide a wand along a course without making contact.
original_url: https://codeclubprojects.org/en-GB/microbit/frustration
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Storing fails
- title: "Challenge: Display an image\t"
- title: Keeping track of fails
- title: Building your game
- title: 'Challenge: Cheat mode!'
- title: 'Challenge: Personalise your game'