---
title: Frustration
hero_image: images/frustration.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
description: Führe einen Zauberstab entlang eines Drahtes, ohne den Draht zu berühren.
original_url: https://codeclubprojects.org/en-GB/microbit/frustration
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: Einleitung
  - 
    title: Berührungen speichern
  - 
    title: 'Herausforderung: Zeige ein Bild an'
  - 
    title: Das Verfolgen von Berührungen
  - 
    title: Baue dein Spiel
  - 
    title: 'Herausforderung: Schummeln!'
  - 
    title: 'Herausforderung: Mache dein Spiel persönlicher'
