---
title: Frustration
hero_image: images/frustration.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
description: Guide une baguette le long de d'un circuit sans le toucher.
original_url: https://codeclubprojects.org/en-GB/microbit/frustration
interests: games
technologies: microbit
site_areas: projets
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Stocker les échecs
  - 
    title: 'Défi : Afficher une image'
  - 
    title: Compter le nombre d'échecs
  - 
    title: Construit ton jeu
  - 
    title: 'Défi: Mode triche !'
  - 
    title: 'Défi: Personnalise ton jeu'
