---
title: Frustration
hero_image: images/frustration.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
description: Guider une baguette le long d'un circuit sans le toucher.
original_url: https://codeclubprojects.org/en-GB/microbit/frustration
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
- title: Introduction
  completion: engaged
- title: Stocker les échecs
- title: 'Défi : Afficher une image'
- title: Garder la trace des échecs
- title: Construire ton jeu
- title: 'Défi : Mode triche !'
  completion: internal
- title: 'Défi : Personnalise ton jeu'
